[package]
name = "notion-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["blocking", "json"] }
futures-io = { version = "0.2.0-beta" }
serde = { version = "1.0.228", features = ["derive"] }
dotenv = "0.15.0"
